meta_product_name: "Plantfam"
meta_title: "Plantfam - For The Love Of Plants"
meta_description: "find a plant sitter and connect with a global community of plant lovers"
meta_image: "PlantCharacter.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
# changed
